name: Postman Repo Sync

on:
  workflow_dispatch:   # run manually from the Actions tab
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v5

      - uses: postman-cs/postman-repo-sync-action@v0
        with:
          project-name: your-service-name
          workspace-id: "190232c5-a08c-4fda-912a-b76242b726f7"
          baseline-collection-id: col-baseline
          smoke-collection-id: col-smoke
          contract-collection-id: col-contract
          environments-json: '["44549813-0bd98294-6456-4958-a121-45ac59a3cc78","44549813-9855e9da-345c-42b3-8c9a-52db0fe472cd"]'
          env-runtime-urls-json: '{"prod":"https://api.example.com","stage":"https://stage.example.com"}'
          postman-api-key: ${{ secrets.POSTMAN_API_KEY }}
          postman-access-token: ${{ secrets.POSTMAN_ACCESS_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
